// Generated by gencpp from file using_markers/environment.msg
// DO NOT EDIT!


#ifndef USING_MARKERS_MESSAGE_ENVIRONMENT_H
#define USING_MARKERS_MESSAGE_ENVIRONMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <using_markers/Polygon.h>

namespace using_markers
{
template <class ContainerAllocator>
struct environment_
{
  typedef environment_<ContainerAllocator> Type;

  environment_()
    : Obstacles()  {
    }
  environment_(const ContainerAllocator& _alloc)
    : Obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::using_markers::Polygon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::using_markers::Polygon_<ContainerAllocator> >::other >  _Obstacles_type;
  _Obstacles_type Obstacles;




  typedef boost::shared_ptr< ::using_markers::environment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::using_markers::environment_<ContainerAllocator> const> ConstPtr;

}; // struct environment_

typedef ::using_markers::environment_<std::allocator<void> > environment;

typedef boost::shared_ptr< ::using_markers::environment > environmentPtr;
typedef boost::shared_ptr< ::using_markers::environment const> environmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::using_markers::environment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::using_markers::environment_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace using_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'using_markers': ['/home/wall-e/Terry_ws/src/haptic-shared-control/using_markers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::using_markers::environment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::using_markers::environment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::using_markers::environment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::using_markers::environment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::using_markers::environment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::using_markers::environment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::using_markers::environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0dbb5e5297239549b759daf57f6ebd35";
  }

  static const char* value(const ::using_markers::environment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0dbb5e5297239549ULL;
  static const uint64_t static_value2 = 0xb759daf57f6ebd35ULL;
};

template<class ContainerAllocator>
struct DataType< ::using_markers::environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "using_markers/environment";
  }

  static const char* value(const ::using_markers::environment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::using_markers::environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# this msg of environment is the information that is used as obstacles\n\
Polygon[] Obstacles\n\
\n\
================================================================================\n\
MSG: using_markers/Polygon\n\
Point2D[] Polygon\n\
\n\
================================================================================\n\
MSG: using_markers/Point2D\n\
# this is a msg about Point2D\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::using_markers::environment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::using_markers::environment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct environment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::using_markers::environment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::using_markers::environment_<ContainerAllocator>& v)
  {
    s << indent << "Obstacles[]" << std::endl;
    for (size_t i = 0; i < v.Obstacles.size(); ++i)
    {
      s << indent << "  Obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::using_markers::Polygon_<ContainerAllocator> >::stream(s, indent + "    ", v.Obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // USING_MARKERS_MESSAGE_ENVIRONMENT_H
