// Generated by gencpp from file using_markers/obstacle_status.msg
// DO NOT EDIT!


#ifndef USING_MARKERS_MESSAGE_OBSTACLE_STATUS_H
#define USING_MARKERS_MESSAGE_OBSTACLE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace using_markers
{
template <class ContainerAllocator>
struct obstacle_status_
{
  typedef obstacle_status_<ContainerAllocator> Type;

  obstacle_status_()
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , ax(0.0)
    , ay(0.0)  {
    }
  obstacle_status_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , ax(0.0)
    , ay(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _ax_type;
  _ax_type ax;

   typedef double _ay_type;
  _ay_type ay;




  typedef boost::shared_ptr< ::using_markers::obstacle_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::using_markers::obstacle_status_<ContainerAllocator> const> ConstPtr;

}; // struct obstacle_status_

typedef ::using_markers::obstacle_status_<std::allocator<void> > obstacle_status;

typedef boost::shared_ptr< ::using_markers::obstacle_status > obstacle_statusPtr;
typedef boost::shared_ptr< ::using_markers::obstacle_status const> obstacle_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::using_markers::obstacle_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::using_markers::obstacle_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace using_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'using_markers': ['/home/wall-e/Terry_ws/src/haptic-shared-control/using_markers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::using_markers::obstacle_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::using_markers::obstacle_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::using_markers::obstacle_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::using_markers::obstacle_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::using_markers::obstacle_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::using_markers::obstacle_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::using_markers::obstacle_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b7969c2a1c161c5211dd9efaef48664";
  }

  static const char* value(const ::using_markers::obstacle_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b7969c2a1c161c5ULL;
  static const uint64_t static_value2 = 0x211dd9efaef48664ULL;
};

template<class ContainerAllocator>
struct DataType< ::using_markers::obstacle_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "using_markers/obstacle_status";
  }

  static const char* value(const ::using_markers::obstacle_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::using_markers::obstacle_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# this is a msg about Point2D\n\
float64 x\n\
float64 y\n\
float64 vx\n\
float64 vy\n\
float64 ax\n\
float64 ay\n\
";
  }

  static const char* value(const ::using_markers::obstacle_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::using_markers::obstacle_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.ax);
      stream.next(m.ay);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacle_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::using_markers::obstacle_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::using_markers::obstacle_status_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "ax: ";
    Printer<double>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<double>::stream(s, indent + "  ", v.ay);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USING_MARKERS_MESSAGE_OBSTACLE_STATUS_H
