# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner/manager_msgs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class manager_msgs(genpy.Message):
  _md5sum = "ac5a6f3bc967fa7c59d9fce13690555f"
  _type = "planner/manager_msgs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# this is a msg from the manager
bool flag
float64 radius
float64 obs_x
float64 obs_y
float64 agent_x
float64 agent_y
"""
  __slots__ = ['flag','radius','obs_x','obs_y','agent_x','agent_y']
  _slot_types = ['bool','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       flag,radius,obs_x,obs_y,agent_x,agent_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(manager_msgs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.flag is None:
        self.flag = False
      if self.radius is None:
        self.radius = 0.
      if self.obs_x is None:
        self.obs_x = 0.
      if self.obs_y is None:
        self.obs_y = 0.
      if self.agent_x is None:
        self.agent_x = 0.
      if self.agent_y is None:
        self.agent_y = 0.
    else:
      self.flag = False
      self.radius = 0.
      self.obs_x = 0.
      self.obs_y = 0.
      self.agent_x = 0.
      self.agent_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B5d.pack(_x.flag, _x.radius, _x.obs_x, _x.obs_y, _x.agent_x, _x.agent_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.flag, _x.radius, _x.obs_x, _x.obs_y, _x.agent_x, _x.agent_y,) = _struct_B5d.unpack(str[start:end])
      self.flag = bool(self.flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B5d.pack(_x.flag, _x.radius, _x.obs_x, _x.obs_y, _x.agent_x, _x.agent_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.flag, _x.radius, _x.obs_x, _x.obs_y, _x.agent_x, _x.agent_y,) = _struct_B5d.unpack(str[start:end])
      self.flag = bool(self.flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B5d = struct.Struct("<B5d")
